"""The built-in currencies (ISO 4217): the same for every user, changed only through migrations.

Everything else a user holds (stocks, funds, coins) is their own commodity.
"""

from uuid import NAMESPACE_DNS, UUID, uuid5


# (code, name, kind, decimals, symbol)
SEED_COMMODITIES: tuple[tuple[str, str, str, int, str | None], ...] = (
    ("AED", "UAE Dirham", "currency", 2, None),
    ("AFN", "Afghan Afghani", "currency", 2, None),
    ("ALL", "Albanian Lek", "currency", 2, None),
    ("AMD", "Armenian Dram", "currency", 2, None),
    ("ANG", "Netherlands Antillean Guilder", "currency", 2, None),
    ("AOA", "Angolan Kwanza", "currency", 2, None),
    ("ARS", "Argentine Peso", "currency", 2, None),
    ("AUD", "Australian Dollar", "currency", 2, "A$"),
    ("AWG", "Aruban Florin", "currency", 2, None),
    ("AZN", "Azerbaijani Manat", "currency", 2, None),
    ("BAM", "Bosnia-Herzegovina Convertible Mark", "currency", 2, None),
    ("BBD", "Barbadian Dollar", "currency", 2, None),
    ("BDT", "Bangladeshi Taka", "currency", 2, None),
    ("BGN", "Bulgarian Lev", "currency", 2, None),
    ("BHD", "Bahraini Dinar", "currency", 3, None),
    ("BIF", "Burundian Franc", "currency", 0, None),
    ("BMD", "Bermudian Dollar", "currency", 2, None),
    ("BND", "Brunei Dollar", "currency", 2, None),
    ("BOB", "Bolivian Boliviano", "currency", 2, None),
    ("BRL", "Brazilian Real", "currency", 2, "R$"),
    ("BSD", "Bahamian Dollar", "currency", 2, None),
    ("BTN", "Bhutanese Ngultrum", "currency", 2, None),
    ("BWP", "Botswana Pula", "currency", 2, None),
    ("BYN", "Belarusian Ruble", "currency", 2, None),
    ("BZD", "Belize Dollar", "currency", 2, None),
    ("CAD", "Canadian Dollar", "currency", 2, "C$"),
    ("CDF", "Congolese Franc", "currency", 2, None),
    ("CHF", "Swiss Franc", "currency", 2, None),
    ("CLP", "Chilean Peso", "currency", 0, None),
    ("CNY", "Chinese Yuan", "currency", 2, "CN¥"),
    ("COP", "Colombian Peso", "currency", 2, None),
    ("CRC", "Costa Rican Colon", "currency", 2, None),
    ("CUP", "Cuban Peso", "currency", 2, None),
    ("CVE", "Cape Verdean Escudo", "currency", 2, None),
    ("CZK", "Czech Koruna", "currency", 2, None),
    ("DJF", "Djiboutian Franc", "currency", 0, None),
    ("DKK", "Danish Krone", "currency", 2, None),
    ("DOP", "Dominican Peso", "currency", 2, None),
    ("DZD", "Algerian Dinar", "currency", 2, None),
    ("EGP", "Egyptian Pound", "currency", 2, None),
    ("ERN", "Eritrean Nakfa", "currency", 2, None),
    ("ETB", "Ethiopian Birr", "currency", 2, None),
    ("EUR", "Euro", "currency", 2, "€"),
    ("FJD", "Fijian Dollar", "currency", 2, None),
    ("FKP", "Falkland Islands Pound", "currency", 2, None),
    ("GBP", "Pound Sterling", "currency", 2, "£"),
    ("GEL", "Georgian Lari", "currency", 2, None),
    ("GHS", "Ghanaian Cedi", "currency", 2, None),
    ("GIP", "Gibraltar Pound", "currency", 2, None),
    ("GMD", "Gambian Dalasi", "currency", 2, None),
    ("GNF", "Guinean Franc", "currency", 0, None),
    ("GTQ", "Guatemalan Quetzal", "currency", 2, None),
    ("GYD", "Guyanese Dollar", "currency", 2, None),
    ("HKD", "Hong Kong Dollar", "currency", 2, "HK$"),
    ("HNL", "Honduran Lempira", "currency", 2, None),
    ("HTG", "Haitian Gourde", "currency", 2, None),
    ("HUF", "Hungarian Forint", "currency", 2, None),
    ("IDR", "Indonesian Rupiah", "currency", 2, None),
    ("ILS", "Israeli New Shekel", "currency", 2, None),
    ("INR", "Indian Rupee", "currency", 2, "₹"),
    ("IQD", "Iraqi Dinar", "currency", 3, None),
    ("IRR", "Iranian Rial", "currency", 2, None),
    ("ISK", "Icelandic Krona", "currency", 0, None),
    ("JMD", "Jamaican Dollar", "currency", 2, None),
    ("JOD", "Jordanian Dinar", "currency", 3, None),
    ("JPY", "Japanese Yen", "currency", 0, "¥"),
    ("KES", "Kenyan Shilling", "currency", 2, None),
    ("KGS", "Kyrgyzstani Som", "currency", 2, None),
    ("KHR", "Cambodian Riel", "currency", 2, None),
    ("KMF", "Comorian Franc", "currency", 0, None),
    ("KPW", "North Korean Won", "currency", 2, None),
    ("KRW", "South Korean Won", "currency", 0, None),
    ("KWD", "Kuwaiti Dinar", "currency", 3, None),
    ("KYD", "Cayman Islands Dollar", "currency", 2, None),
    ("KZT", "Kazakhstani Tenge", "currency", 2, None),
    ("LAK", "Lao Kip", "currency", 2, None),
    ("LBP", "Lebanese Pound", "currency", 2, None),
    ("LKR", "Sri Lankan Rupee", "currency", 2, None),
    ("LRD", "Liberian Dollar", "currency", 2, None),
    ("LSL", "Lesotho Loti", "currency", 2, None),
    ("LYD", "Libyan Dinar", "currency", 3, None),
    ("MAD", "Moroccan Dirham", "currency", 2, None),
    ("MDL", "Moldovan Leu", "currency", 2, None),
    ("MGA", "Malagasy Ariary", "currency", 2, None),
    ("MKD", "Macedonian Denar", "currency", 2, None),
    ("MMK", "Myanmar Kyat", "currency", 2, None),
    ("MNT", "Mongolian Tugrik", "currency", 2, None),
    ("MOP", "Macanese Pataca", "currency", 2, None),
    ("MRU", "Mauritanian Ouguiya", "currency", 2, None),
    ("MUR", "Mauritian Rupee", "currency", 2, None),
    ("MVR", "Maldivian Rufiyaa", "currency", 2, None),
    ("MWK", "Malawian Kwacha", "currency", 2, None),
    ("MXN", "Mexican Peso", "currency", 2, None),
    ("MYR", "Malaysian Ringgit", "currency", 2, None),
    ("MZN", "Mozambican Metical", "currency", 2, None),
    ("NAD", "Namibian Dollar", "currency", 2, None),
    ("NGN", "Nigerian Naira", "currency", 2, None),
    ("NIO", "Nicaraguan Cordoba", "currency", 2, None),
    ("NOK", "Norwegian Krone", "currency", 2, None),
    ("NPR", "Nepalese Rupee", "currency", 2, None),
    ("NZD", "New Zealand Dollar", "currency", 2, "NZ$"),
    ("OMR", "Omani Rial", "currency", 3, None),
    ("PAB", "Panamanian Balboa", "currency", 2, None),
    ("PEN", "Peruvian Sol", "currency", 2, None),
    ("PGK", "Papua New Guinean Kina", "currency", 2, None),
    ("PHP", "Philippine Peso", "currency", 2, None),
    ("PKR", "Pakistani Rupee", "currency", 2, None),
    ("PLN", "Polish Zloty", "currency", 2, None),
    ("PYG", "Paraguayan Guarani", "currency", 0, None),
    ("QAR", "Qatari Riyal", "currency", 2, None),
    ("RON", "Romanian Leu", "currency", 2, None),
    ("RSD", "Serbian Dinar", "currency", 2, None),
    ("RUB", "Russian Ruble", "currency", 2, None),
    ("RWF", "Rwandan Franc", "currency", 0, None),
    ("SAR", "Saudi Riyal", "currency", 2, None),
    ("SBD", "Solomon Islands Dollar", "currency", 2, None),
    ("SCR", "Seychellois Rupee", "currency", 2, None),
    ("SDG", "Sudanese Pound", "currency", 2, None),
    ("SEK", "Swedish Krona", "currency", 2, None),
    ("SGD", "Singapore Dollar", "currency", 2, "S$"),
    ("SHP", "Saint Helena Pound", "currency", 2, None),
    ("SLE", "Sierra Leonean Leone", "currency", 2, None),
    ("SOS", "Somali Shilling", "currency", 2, None),
    ("SRD", "Surinamese Dollar", "currency", 2, None),
    ("SSP", "South Sudanese Pound", "currency", 2, None),
    ("STN", "Sao Tome and Principe Dobra", "currency", 2, None),
    ("SVC", "Salvadoran Colon", "currency", 2, None),
    ("SYP", "Syrian Pound", "currency", 2, None),
    ("SZL", "Swazi Lilangeni", "currency", 2, None),
    ("THB", "Thai Baht", "currency", 2, None),
    ("TJS", "Tajikistani Somoni", "currency", 2, None),
    ("TMT", "Turkmenistani Manat", "currency", 2, None),
    ("TND", "Tunisian Dinar", "currency", 3, None),
    ("TOP", "Tongan Paanga", "currency", 2, None),
    ("TRY", "Turkish Lira", "currency", 2, None),
    ("TTD", "Trinidad and Tobago Dollar", "currency", 2, None),
    ("TWD", "New Taiwan Dollar", "currency", 2, None),
    ("TZS", "Tanzanian Shilling", "currency", 2, None),
    ("UAH", "Ukrainian Hryvnia", "currency", 2, None),
    ("UGX", "Ugandan Shilling", "currency", 0, None),
    ("USD", "US Dollar", "currency", 2, "$"),
    ("UYU", "Uruguayan Peso", "currency", 2, None),
    ("UZS", "Uzbekistani Som", "currency", 2, None),
    ("VES", "Venezuelan Bolivar", "currency", 2, None),
    ("VND", "Vietnamese Dong", "currency", 0, None),
    ("VUV", "Vanuatu Vatu", "currency", 0, None),
    ("WST", "Samoan Tala", "currency", 2, None),
    ("XAF", "Central African CFA Franc", "currency", 0, None),
    ("XCD", "East Caribbean Dollar", "currency", 2, None),
    ("XOF", "West African CFA Franc", "currency", 0, None),
    ("XPF", "CFP Franc", "currency", 0, None),
    ("YER", "Yemeni Rial", "currency", 2, None),
    ("ZAR", "South African Rand", "currency", 2, None),
    ("ZMW", "Zambian Kwacha", "currency", 2, None),
    ("ZWG", "Zimbabwe Gold", "currency", 2, None),
)

DEFAULT_CURRENCY_CODE = "INR"


def seed_id(code: str) -> UUID:
    """Global commodities have the same id in every database."""
    return uuid5(NAMESPACE_DNS, f"{code}.commodities.finode")


def seed_rows(now) -> list[dict]:
    return [
        {
            "cid": seed_id(code),
            "user": None,
            "code": code,
            "name": name,
            "kind": kind,
            "decimals": decimals,
            "symbol": symbol,
            "created": now,
            "updated": now,
        }
        for code, name, kind, decimals, symbol in SEED_COMMODITIES
    ]
