"""add timestamp columns

Revision ID: e8abc44de1c4
Revises: 00ac92f0c6fc
Create Date: 2026-05-16 11:13:40.303000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8abc44de1c4'
down_revision: Union[str, Sequence[str], None] = '00ac92f0c6fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    for table_name in ("accounts", "categories", "transactions"):
        op.add_column(
            table_name,
            sa.Column(
                "created",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text("CURRENT_TIMESTAMP"),
            ),
        )
        op.add_column(
            table_name,
            sa.Column(
                "updated",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text("CURRENT_TIMESTAMP"),
            ),
        )
        op.alter_column(table_name, "created", server_default=None)
        op.alter_column(table_name, "updated", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'updated')
    op.drop_column('transactions', 'created')
    op.drop_column('categories', 'updated')
    op.drop_column('categories', 'created')
    op.drop_column('accounts', 'updated')
    op.drop_column('accounts', 'created')
    # ### end Alembic commands ###
